language: python
python:
  - "3.6.1"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests (python setup.py test)
script:
  nosetests
after_success:
  coveralls
notifications:
  email: false